baseURL = "https://hanyu.cool/lifeblog/"
languageCode = "zh-cn"
title = " 韩西瓜 | 开心 "
theme = "hugo-PaperMod"
summaryLength = 70
hasCJKLanguage = true

enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

[author]
  name = "hanyu."
  weibo = "https://weibo.com/sohanyu"



[params]
  #extraHead = '<script src="xxxx.js"></script>'
  #extraCSSFiles = ["css/foo.css", "css/bar.css"]
  description = "Log something useless, but interesting."
  mainSections = ["posts"]
  headTitle = "hey, dude."
  base = "https://hanyu.cool/lifeblog/"



[[params.socials]]
name = "Home / "
link = "/"

[[params.socials]]
name = "Blog / "
link = "/lifeblog/"

[[params.socials]]
name = "About"
link = "/lifeblog/about/"



#postHeaderContent = ""
#postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"


